#!/usr/bin/perl
if ($ARGV[0] eq '') { print "usage\n  sgf_diagram <sgffile>\n"; }
open OUT, '>sgf_diagram.csv';
for (1..400)
{
  $out = `gnugo --score estimate -l $ARGV[0] -L $_`;
  $out =~ /(\d+.\d+)/;
  $res = $1;
  if ($out =~ /white/i) { $res = -1 * $res; }
  $filt = ($prev + $res)/2;
  $prev = $res;
  print "$_\t$filt\t$res\n";
  print OUT "$_\t$filt\t$res\n";
}
close OUT;
open GPLT, '|gnuplot -persist';
print GPLT 'set ylabel "black points - white points"';
print GPLT 'set xlabel "moves"';
print GPLT 'plot "sgf_diagram.csv" u 1:3 w l lc 2 t "", "sgf_diagram.csv" u 1:2 w l lc 1 t ""';

